### ISSUE TITLE
スマホ表示の際に表の文字をスクロール表示したい

### ISSUE THREAD

**Issue by namekoed** [fukuchiharuki/LuLu-a-skin-for-PukiWiki#13]
初めまして。
luluスキンを有り難く使用させて頂いております。

件名の通り、本スキンをpukiwikiに反映致した際に、表テーブル内の文字がセル内で折り返して表示されます。（また、折り返えされた文字はcontents外をはみ出します）

セル内で折り返しすのではなく、スクロールにて表現させたいのですが何か良い方法はありますでしょうか。
よろしくお願いします。

**Comment by fukuchiharuki** [comment]
https://github.com/fukuchiharuki/LuLu-a-skin-for-PukiWiki/pull/14
`table`を出力するところが`.ie5`でラップしているようなので、
そこに`overflow`を設定してみました、どうでしょうか。

**Comment by namekoed** [comment]
fukuchiharukiさま

御返事ありがとうございます。
修正して頂きましたファイルにて確認させてもらったところ、
無事、PCのブラウザ（IE11やGoogle Chrome）ではスクロールバーが表示されるようになりました！
ですが、スマホ（AndroidのChrome）においては相変わらず文字が折り返され、はみ出した状態となっております。

何かヒントがありましたらご教授頂けないでしょうか。
お手間お掛けして申し訳ございません・・・。

**Comment by fukuchiharuki** [comment]
セル中の改行を一切なくしたいということですね。
ちょっと試してみてまた週末にでもあげてみますね。
（手が遅くて申し訳ないです＞＜）

**Comment by namekoed** [comment]
fukuchiharukiさま

お忙しい中、ご対応頂きまして恐縮です。
本日、スマホで再度スキンを確認したところ、何故か問題なく折り返さずスクロールバーが表示されました。
（特に弄った訳ではなく、原因が不明で申し訳ございません。）

その代わりではないですが、今度は表以外の文字も一切折り返さずに表示されるようになっておりました。
中途半端な状況報告で申し訳ございませんが、お手隙の時に確認して頂ければ幸いです。

よろしくお願い致します。

**Comment by fukuchiharuki** [comment]
https://github.com/fukuchiharuki/LuLu-a-skin-for-PukiWiki/pull/15 にて修正（のつもり）。
