### ISSUE TITLE
ページ内ジャンプが不調な件

### ISSUE THREAD

**Issue by hagatana** [fukuchiharuki/LuLu-a-skin-for-PukiWiki#7]
素敵なテーマをありがとうございます。
今試してみているのですが、#contentsで生成された目次から該当箇所へジャンプできないのです。
web上からローカルに保存して試すとジャンプ出来るのです。
cssの記述なのかなとか思いますが、心当たりございませんでしょうか。
初めてのコメントなので書く場所がここで良いのか不安です。
もし場違いでしたらごめんなさい。

**Comment by fukuchiharuki** [comment]
コメントありがとうございます！
まさにテーマをガラッと変えようとしてるタイミングでしたが、
2時間前でしたらMaterial Design Lightを使うようにしたものですよね。

#contentsが生成する目次から該当箇所へジャンプができない件、
ご指摘の通り、cssの記述のせいでした。
アンカーが張られている箇所を「display: none;」すると飛べなくなってしまうようです。
ので、「visibility: hidden;」にして要素はそこにあるようにすると解決することができました。

この修正はコミットしましたので、最新で確認してみてください。
https://github.com/fukuchiharuki/LuLu-a-skin-for-PukiWiki/commit/ec0ebf96d373a358a4494007b6aa44414095141c

**Comment by hagatana** [comment]
さっそくありがとうございます。
この症状、以前のスキンでも確認できていたのですが綺麗に解消しました。
#contentsリストからのページジャンプと、ジャンプ先から「戻る」でリストへ戻るのを確認できました。
ありがとうございます。
今回のスキン、スマートすぎて見惚れます。

**Comment by hagatana** [comment]
今朝朝イチで確認した時はジャンプ先からも戻ったのですが、今見ると戻らなくなっていました。
リストからジャンプした後に戻る操作をすると、ブラウザのアドレスバーは元の(IDの付いていない素の)アドレスに戻っていますが、ページの表示されている場所はジャンプ先のままなのです。
この奇妙な状況はおそらくブラウザ環境だろうと思ったのですが、FirefoxもChromeもモバイルChromeも戻りませんでした。
ブラウザの「戻る」ですからvisibility:hiddenやdisplay:noneとは無関係っぽいのですが、何か他にも要因があるものでしょうか。

追記
https://goo.gl/bT7j6w
↑に今回の私と似た症状(当方はスクロールとは無関係です)が挙げられていましたけど6年間ノータッチでした。

**Comment by fukuchiharuki** [comment]
ほんとですね、戻りがおかしい。

MDLの作りがそうなっているようですが、
最初の読み込みが完了するとスクロールが先頭になってしまうのも
かなり気になっています。。

いずれもパッと分からないのでまたスキンを作り変えるかもです。すみません。

**Comment by fukuchiharuki** [comment]
MDLが「.mdl-js-layout」に仕掛けるjavascriptが
スクロール周辺に不具合を起こすようです。
メニューの動作とウィンドウサイズのマーキングを自前で実装しました。

で、回避できたと思うのですが、どうでしょう。

**Comment by hagatana** [comment]
凄いです。
何事もなかったかのように戻ります。
Firefox,chrome,Androidchrome全て完璧です。
ありがとうございます。

ふと、左上のドロワーメニューが消えてません？

**Comment by fukuchiharuki** [comment]
ドロワーメニュー出ませんか？
http://fukuchiharuki.me/lulu/ で動作確認はしてみていて、
出てきているのですが。

**Comment by hagatana** [comment]
わ。
出てますね。
これは私が何かしたっぽいです。洗い直します。
余計なお時間を割かせてしまいました。
すみません。

**Comment by hagatana** [comment]
速攻で判明しました。
jsをアップロードし忘れてました。
ドロワーメニューも出て来ました。
ありがとうございますm(_ _)m
PukiWiki+LuLuskin、最高すぎます。

**Comment by fukuchiharuki** [comment]
よかったです！
今回、MDLの気持ち悪い挙動を回避することができたので非常に助かりました。

PukiWikiよいですよね！

**Comment by fukuchiharuki** [comment]
クローズしますね。
また何かありましたらチケットあげてください！
